site_name: HTML Basics Demo
site_url: https://htmlDemo.ca

nav:
  - Home: index.md
  - Setup: VsCode Installation.md
  - Your First Website: Basic HTML.md
  - Detailing: CSS Basics.md
  - Seeing Results: Live Server.md
  - Glossary: glossary.md
  - Troubleshooting: troubleshooting.md
theme:
  name: material
  font:
    text: Merriweather Sans
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: indigo
      accent: indigo
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: white
      accent: white
